### ISSUE TITLE
The Apache-2.0 License yaml file seem not to be complete (obligation missing)

### ISSUE THREAD

**Issue by OliverFendt** [finos/OSLC-handbook#18]
Section 4 d. of the Apache-2.0 states
"If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License. "

So if you are distributing a modified version of the package AND the package contains a NOTICE file you have to print the content of the NOTICE file in the documentation.
I was not able to find this in the yml file of the Apache-2.0

**Comment by maxhbr** [comment]
See https://github.com/finos-osr/OSLC-handbook/pull/20, which is now merged
