### ISSUE TITLE
Link to Zlib license incorrect

### ISSUE THREAD

**Issue by buxtonpaul** [finos/OSLC-handbook#25]
The licenseid for the Zlib license is incorrect, it isn't using the correct case
It should be

 licenseId: Zlib 
not
 licenseId: zlib

in 
https://github.com/finos/OSLC-handbook/blob/master/src/zlib.yaml

**Comment by mindthegab** [comment]
@copiesofcopies FYI

**Comment by copiesofcopies** [comment]
Fixed, thanks for the heads up!
